#!/usr/bin/env python3
"""Compare cgo calls in this module with the public igraph C API."""

import argparse
import collections
import json
import pathlib
import re
import tarfile
import tempfile
import urllib.request


ROOT = pathlib.Path(__file__).resolve().parents[1]
CONFIG = ROOT / "coverage.json"
DECLARATION = re.compile(r"\bIGRAPH_EXPORT\b[\s\w*]+?\b(igraph_[a-zA-Z0-9_]+)\s*\(")
CALL = re.compile(r"\bC\.(igraph_[a-zA-Z0-9_]+)\s*\(")


def public_api(include_dir):
    functions = {}
    for header in sorted(pathlib.Path(include_dir).glob("igraph*.h")):
        text = header.read_text(encoding="utf-8", errors="replace")
        for name in DECLARATION.findall(text):
            functions.setdefault(name, header.name)
    return functions


def cgo_calls(root):
    calls = collections.defaultdict(list)
    for path in sorted(root.glob("*.go")):
        if path.name.endswith("_test.go"):
            continue
        text = path.read_text(encoding="utf-8")
        for match in CALL.finditer(text):
            line = text.count("\n", 0, match.start()) + 1
            calls[match.group(1)].append(f"{path.name}:{line}")
    return calls


def acquire_source(config, source):
    if source:
        return pathlib.Path(source), None
    temp = tempfile.TemporaryDirectory(prefix="igraph-api-")
    archive = pathlib.Path(temp.name) / "igraph.tar.gz"
    urllib.request.urlretrieve(config["archive_url"], archive)
    with tarfile.open(archive) as tar:
        tar.extractall(temp.name, filter="data")
    children = [p for p in pathlib.Path(temp.name).iterdir() if p.is_dir()]
    if len(children) != 1:
        raise RuntimeError("archive must contain exactly one top-level directory")
    return children[0], temp


def render(config, api, calls):
    covered = sorted(set(api) & set(calls))
    unknown = sorted(set(calls) - set(api))
    percent = 100 * len(covered) / len(api) if api else 0
    groups = collections.defaultdict(lambda: [0, 0])
    for name, header in api.items():
        groups[header][1] += 1
        groups[header][0] += name in calls

    lines = [
        "# igraph exported C API coverage",
        "",
        "<!-- Generated by tools/api_coverage.py; do not edit manually. -->",
        "",
        f"Upstream: [igraph {config['version']}]({config['release_url']})",
        "",
        f"**{len(covered)} / {len(api)} explicitly exported C functions covered ({percent:.2f}%)**",
        "",
        "The denominator is the set of `IGRAPH_EXPORT` declarations with literal `igraph_*` names in upstream "
        "headers. A function is covered when production Go code calls that name via cgo. Template-generated "
        "APIs (notably typed vectors) are intentionally outside the denominator. This is a mechanical inventory, "
        "not a claim of behavioral or test coverage.",
        "",
        "## Coverage by upstream header",
        "",
        "| Header | Covered | Total | Coverage |",
        "|---|---:|---:|---:|",
    ]
    for header, (done, total) in sorted(groups.items()):
        lines.append(f"| `{header}` | {done} | {total} | {100 * done / total:.2f}% |")
    lines += ["", "## Covered functions", ""]
    lines += [f"- `{name}` ({', '.join(calls[name])})" for name in covered] or ["_None._"]
    lines += ["", "## Calls without a literal exported declaration", ""]
    lines += [f"- `{name}` ({', '.join(calls[name])})" for name in unknown] or ["_None._"]
    lines += [
        "",
        "These calls may be template-generated, private, renamed, or removed upstream and should be reviewed during upgrades.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", help="local igraph source tree (avoids downloading)")
    parser.add_argument("--output", default="COVERAGE.md", help="report path, or - for stdout")
    args = parser.parse_args()
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    source, temporary = acquire_source(config, args.source)
    try:
        api = public_api(source / "include")
        if not api:
            raise RuntimeError(f"no public declarations found under {source / 'include'}")
        report = render(config, api, cgo_calls(ROOT))
    finally:
        if temporary:
            temporary.cleanup()
    if args.output == "-":
        print(report)
    else:
        (ROOT / args.output).write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
