#!/usr/bin/env python3
"""Build and validate the explicit go-igraph upstream binding inventory."""

from __future__ import annotations

import argparse
import sys
import tempfile
from collections import Counter
from pathlib import Path

from upstream_api import (
    Annotation,
    discover_annotations,
    discover_go_calls,
    discover_upstream_api,
    download_or_get_source,
    load_config,
    locate_include,
)


def validate_inventory(
    declarations: dict[str, str], calls: set[str], annotations: list[Annotation], unsupported: set[str]
) -> None:
    errors: list[str] = []
    known = set(declarations)
    for annotation in annotations:
        if annotation.upstream not in known:
            errors.append(f"{annotation.path}:{annotation.line}: unknown upstream symbol {annotation.upstream}")
        if annotation.kind == "bind" and not annotation.go_symbol[:1].isupper():
            errors.append(f"{annotation.path}:{annotation.line}: binding target {annotation.go_symbol} is not exported")
    by_upstream = Counter(item.upstream for item in annotations)
    errors.extend(f"duplicate annotation for {name}" for name, count in sorted(by_upstream.items()) if count > 1)
    errors.extend(f"unknown intentionally unsupported symbol {name}" for name in sorted(unsupported - known))
    classified = {item.upstream for item in annotations} | unsupported
    errors.extend(f"unclassified production C call {name}" for name in sorted(calls - classified))
    if errors:
        raise ValueError("invalid binding inventory:\n- " + "\n- ".join(errors))


def render(config: dict, declarations: dict[str, str], annotations: list[Annotation]) -> str:
    bindings = {item.upstream: item for item in annotations if item.kind == "bind"}
    internal = {item.upstream: item for item in annotations if item.kind == "internal"}
    unsupported = set(config.get("intentionally_unsupported", []))
    total = len(declarations)
    percent = 100 * len(bindings) / total if total else 0
    by_header = Counter(declarations.values())
    bound_by_header = Counter(declarations[name] for name in bindings)
    lines = [
        "# Upstream igraph API coverage", "",
        "> Generated by `tools/api_coverage.py`; do not edit by hand.", "",
        f"- Upstream: [{config['upstream']} {config['version']}]({config['release_url']})",
        f"- User-facing bindings: **{len(bindings)} / {total} ({percent:.2f}%)**",
        f"- Internal dependencies: **{len(internal)}**",
        f"- Intentionally unsupported: **{len(unsupported)}**", "",
        "Coverage is based on explicit `//igraph:bind` annotations on exported Go declarations.", "",
        "Headers marked `(generated)` are declaration-discovery locations. PMT-generated",
        "APIs can appear through several public headers, so the report records the first",
        "preprocessed header where each declaration is found rather than a canonical owner.", "",
        "## Summary by header", "", "| Header | Bound | Total | Coverage |",
        "| --- | ---: | ---: | ---: |",
    ]
    for header in sorted(by_header):
        count, header_total = bound_by_header[header], by_header[header]
        lines.append(f"| `{header}` | {count} | {header_total} | {100 * count / header_total:.2f}% |")
    lines += ["", "## Function inventory", "", "| Function | Header | Status | Go API |", "| --- | --- | --- | --- |"]
    for name in sorted(declarations):
        if name in bindings:
            status, owner = "User-facing", f"`{bindings[name].go_symbol}`"
        elif name in internal:
            status, owner = "Internal", f"`{internal[name].go_symbol}`"
        elif name in unsupported:
            status, owner = "Intentionally unsupported", "—"
        else:
            status, owner = "Missing", "—"
        lines.append(f"| `{name}` | `{declarations[name]}` | {status} | {owner} |")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=Path("tools/api_coverage_config.json"))
    parser.add_argument("--source-dir", type=Path, help="local igraph source tree (offline mode)")
    parser.add_argument("--output", type=Path, default=Path("docs/api-coverage.md"))
    parser.add_argument("--check", action="store_true", help="fail if the generated report differs")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo = Path(__file__).resolve().parents[1]
    config = load_config(args.config)
    output = args.output if args.output.is_absolute() else repo / args.output
    calls, annotations = discover_go_calls(repo), discover_annotations(repo)
    if args.source_dir:
        source = args.source_dir
    else:
        source = download_or_get_source(config)
    declarations = discover_upstream_api(locate_include(source))
    try:
        validate_inventory(declarations, calls, annotations, set(config.get("intentionally_unsupported", [])))
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    report = render(config, declarations, annotations)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != report:
            print(f"{output} is out of date; run make coverage", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")
    print(f"wrote {output}: {sum(a.kind == 'bind' for a in annotations)}/{len(declarations)} user-facing bindings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
