#!/usr/bin/env python3
"""Compare upstream igraph's exported C API with calls made by go-igraph."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tarfile
import tempfile
import urllib.request
from collections import Counter
from pathlib import Path

EXPORT_RE = re.compile(
    r"^\s*(?:(?:IGRAPH_EXPERIMENTAL|IGRAPH_DEPRECATED)\s+)?IGRAPH_EXPORT"
    r"(?:(?!;).)*?\b(igraph_[A-Za-z0-9_]+)\s*\(",
    re.MULTILINE | re.DOTALL,
)
CALL_RE = re.compile(r"\bC\.(igraph_[A-Za-z0-9_]+)\s*\(")


def strip_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/|//[^\n]*", "", text, flags=re.DOTALL)


def discover_upstream_api(include_dir: Path) -> dict[str, str]:
    declarations: dict[str, str] = {}
    for header in sorted(include_dir.rglob("*.h")):
        text = strip_comments(header.read_text(encoding="utf-8", errors="replace"))
        for match in EXPORT_RE.finditer(text):
            declarations.setdefault(match.group(1), header.relative_to(include_dir).as_posix())
    return declarations


def production_go_files(repo: Path) -> list[Path]:
    return sorted(
        path for path in repo.rglob("*.go")
        if not path.name.endswith("_test.go") and ".git" not in path.parts
    )


def discover_go_calls(repo: Path) -> set[str]:
    calls: set[str] = set()
    for path in production_go_files(repo):
        calls.update(CALL_RE.findall(path.read_text(encoding="utf-8")))
    return calls


def locate_include(source: Path) -> Path:
    direct = source / "include"
    if direct.is_dir():
        return direct
    candidates = list(source.glob("*/include"))
    if len(candidates) == 1:
        return candidates[0]
    raise ValueError(f"could not locate a unique include directory below {source}")


def download_source(url: str, destination: Path) -> Path:
    archive = destination / "upstream.tar.gz"
    urllib.request.urlretrieve(url, archive)
    with tarfile.open(archive, "r:gz") as bundle:
        root = destination.resolve()
        for member in bundle.getmembers():
            target = (destination / member.name).resolve()
            if root not in target.parents and target != root:
                raise ValueError("unsafe path in upstream archive")
        bundle.extractall(destination, filter="data")
    return destination


def render(config: dict[str, str], declarations: dict[str, str], calls: set[str]) -> str:
    covered = sorted(calls & declarations.keys())
    unknown = sorted(calls - declarations.keys())
    total = len(declarations)
    percent = 100 * len(covered) / total if total else 0
    by_header = Counter(declarations.values())
    covered_by_header = Counter(declarations[name] for name in covered)

    lines = [
        "# Upstream igraph API coverage",
        "",
        "> Generated by `tools/api_coverage.py`; do not edit by hand.",
        "",
        f"- Upstream: [{config['upstream']} {config['version']}]({config['release_url']})",
        f"- Covered exported functions: **{len(covered)} / {total} ({percent:.2f}%)**",
        "- Coverage means that production Go code directly calls the exported C function.",
        "  It does not measure API quality, behavioral parity, constants, types, or macros.",
        "",
        "## Summary by header",
        "",
        "| Header | Covered | Total | Coverage |",
        "| --- | ---: | ---: | ---: |",
    ]
    for header in sorted(by_header):
        count = covered_by_header[header]
        header_total = by_header[header]
        lines.append(f"| `{header}` | {count} | {header_total} | {100 * count / header_total:.2f}% |")

    lines += ["", "## Function inventory", "", "| Function | Header | Status |", "| --- | --- | --- |"]
    for name in sorted(declarations):
        status = "Covered" if name in calls else "Missing"
        lines.append(f"| `{name}` | `{declarations[name]}` | {status} |")

    lines += ["", "## Calls not declared as exported functions in this upstream version", ""]
    if unknown:
        lines += [
            "These may have been removed or renamed, or may be generated by macros/templates:",
            "",
            *[f"- `{name}`" for name in unknown],
        ]
    else:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=Path("tools/api_coverage_config.json"))
    parser.add_argument("--source-dir", type=Path, help="local igraph source tree (offline mode)")
    parser.add_argument("--output", type=Path, default=Path("docs/api-coverage.md"))
    parser.add_argument("--check", action="store_true", help="fail if the generated report differs")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo = Path(__file__).resolve().parents[1]
    config = json.loads(args.config.read_text(encoding="utf-8"))
    output = args.output if args.output.is_absolute() else repo / args.output
    calls = discover_go_calls(repo)

    with tempfile.TemporaryDirectory(prefix="go-igraph-coverage-") as temp:
        source = args.source_dir or download_source(config["source_archive_url"], Path(temp))
        declarations = discover_upstream_api(locate_include(source))
        report = render(config, declarations, calls)

    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != report:
            print(f"{output} is out of date; run make coverage", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")
    print(f"wrote {output}: {len(calls & declarations.keys())}/{len(declarations)} covered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
