#!/usr/bin/env python3
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from api_coverage import (
    ConfiguredDisposition,
    configured_dispositions,
    render,
    validate_inventory,
)
from upstream_api import (
    Annotation,
    discover_annotations,
    discover_exported_go_declarations,
    discover_go_calls,
    discover_upstream_api,
    production_go_files,
)


class ApiCoverageTest(unittest.TestCase):
    def test_discovers_multiline_exported_declarations(self):
        with tempfile.TemporaryDirectory() as temp:
            include = Path(temp)
            (include / "igraph_example.h").write_text(
                "IGRAPH_EXPORT igraph_error_t\nigraph_example(const igraph_t *graph);\n"
                "IGRAPH_EXPERIMENTAL IGRAPH_EXPORT igraph_error_t igraph_new_api(void);\n"
                "igraph_error_t igraph_private(void);\n",
                encoding="utf-8",
            )
            self.assertEqual(
                discover_upstream_api(include),
                {
                    "igraph_example": "igraph_example.h",
                    "igraph_new_api": "igraph_example.h",
                },
            )

    @patch("upstream_api.subprocess.run")
    def test_discovers_generated_api_when_another_header_cannot_be_preprocessed(self, run):
        with tempfile.TemporaryDirectory() as temp:
            include = Path(temp)
            (include / "igraph.h").write_text('#include "igraph_version.h"\n', encoding="utf-8")
            (include / "igraph_vector.h").write_text("/* generated by PMT */\n", encoding="utf-8")

            def preprocess(command, **_kwargs):
                class Result:
                    stdout = ""

                result = Result()
                if command[-1].endswith("igraph_vector.h"):
                    result.stdout = "IGRAPH_EXPORT void igraph_vector_destroy(void *v);\n"
                return result

            run.side_effect = preprocess
            self.assertEqual(
                discover_upstream_api(include),
                {"igraph_vector_destroy": "igraph_vector.h (generated)"},
            )

    def test_finds_production_calls_and_excludes_tests(self):
        with tempfile.TemporaryDirectory() as temp:
            repo = Path(temp)
            (repo / "graph.go").write_text("package p\n// C.igraph_real()\n", encoding="utf-8")
            (repo / "graph_test.go").write_text("package p\n// C.igraph_test()\n", encoding="utf-8")
            self.assertEqual([p.name for p in production_go_files(repo)], ["graph.go"])
            self.assertEqual(discover_go_calls(repo), {"igraph_real"})

    def test_discovers_annotations_attached_to_declarations(self):
        with tempfile.TemporaryDirectory() as temp:
            repo = Path(temp)
            (repo / "graph.go").write_text(
                "package p\n"
                "//igraph:bind igraph_empty\n"
                "func NewGraph() {}\n"
                "//igraph:internal igraph_destroy\n"
                "func (g *Graph) close() {}\n",
                encoding="utf-8",
            )
            examples = repo / "examples" / "other"
            examples.mkdir(parents=True)
            (examples / "main.go").write_text(
                "package main\nfunc ExampleOnly() {}\nfunc NewGraph() {}\n",
                encoding="utf-8",
            )
            self.assertEqual(
                discover_annotations(repo),
                [
                    Annotation("bind", "igraph_empty", "NewGraph", "graph.go", 2),
                    Annotation("internal", "igraph_destroy", "close", "graph.go", 4),
                ],
            )
            self.assertEqual(discover_exported_go_declarations(repo), {"NewGraph"})

    def test_rejects_unknown_duplicate_and_unclassified_symbols(self):
        declarations = {"igraph_empty": "igraph.h", "igraph_destroy": "igraph.h"}
        annotations = [
            Annotation("bind", "igraph_empty", "NewGraph", "graph.go", 1),
            Annotation("internal", "igraph_empty", "close", "graph.go", 2),
            Annotation("bind", "igraph_unknown", "Unknown", "graph.go", 3),
        ]
        with self.assertRaisesRegex(ValueError, "duplicate annotation for igraph_empty"):
            validate_inventory(declarations, {"igraph_destroy"}, annotations, {}, {"NewGraph", "Unknown"})

    def test_rejects_binding_on_unexported_go_symbol(self):
        annotation = Annotation("bind", "igraph_empty", "newGraph", "graph.go", 1)
        with self.assertRaisesRegex(ValueError, "binding target newGraph is not exported"):
            validate_inventory({"igraph_empty": "igraph.h"}, set(), [annotation], {}, set())

    def test_parses_structured_configured_dispositions(self):
        config = {
            "dispositions": {
                "composed": {
                    "igraph_composed": {
                        "go_api": "Composed",
                        "domain": "example",
                        "rationale": "One Go operation composes this declaration.",
                    }
                },
                "deferred": {
                    "igraph_deferred": {
                        "domain": "later",
                        "rationale": "This domain has not been implemented yet.",
                    }
                },
                "intentionally_unsupported": {
                    "igraph_unsupported": {
                        "domain": "low-level",
                        "rationale": "The public API does not expose C handles.",
                    }
                },
            }
        }
        self.assertEqual(
            configured_dispositions(config),
            {
                "igraph_composed": ConfiguredDisposition(
                    "composed", "example", "One Go operation composes this declaration.", "Composed"
                ),
                "igraph_deferred": ConfiguredDisposition(
                    "deferred", "later", "This domain has not been implemented yet."
                ),
                "igraph_unsupported": ConfiguredDisposition(
                    "intentionally_unsupported", "low-level", "The public API does not expose C handles."
                ),
            },
        )

    def test_rejects_malformed_and_overlapping_configured_dispositions(self):
        with self.assertRaisesRegex(ValueError, "overlapping configured disposition for igraph_example"):
            configured_dispositions(
                {
                    "dispositions": {
                        "composed": {
                            "igraph_example": {
                                "go_api": "Example",
                                "domain": "example",
                                "rationale": "Composed.",
                            }
                        },
                        "deferred": {
                            "igraph_example": {
                                "domain": "example",
                                "rationale": "Deferred.",
                            }
                        },
                    }
                }
            )
        with self.assertRaisesRegex(ValueError, "requires an exported Go API"):
            configured_dispositions(
                {
                    "dispositions": {
                        "composed": {
                            "igraph_example": {
                                "go_api": "example",
                                "domain": "example",
                                "rationale": "Composed.",
                            }
                        }
                    }
                }
            )
        with self.assertRaisesRegex(ValueError, "requires a non-empty rationale"):
            configured_dispositions(
                {
                    "dispositions": {
                        "deferred": {"igraph_example": {"domain": "example", "rationale": ""}}
                    }
                }
            )

    def test_rejects_unknown_overlap_and_deferred_production_calls(self):
        declarations = {
            "igraph_bound": "a.h",
            "igraph_deferred": "a.h",
        }
        annotation = Annotation("bind", "igraph_bound", "Bound", "graph.go", 1)
        with self.assertRaisesRegex(ValueError, "overlapping annotation and configured disposition"):
            validate_inventory(
                declarations,
                set(),
                [annotation],
                {"igraph_bound": ConfiguredDisposition("deferred", "example", "Later.")},
                {"Bound"},
            )
        with self.assertRaisesRegex(ValueError, "unknown configured disposition symbol"):
            validate_inventory(
                declarations,
                set(),
                [],
                {"igraph_unknown": ConfiguredDisposition("deferred", "example", "Later.")},
                set(),
            )
        with self.assertRaisesRegex(ValueError, "unclassified production C call igraph_deferred"):
            validate_inventory(
                declarations,
                {"igraph_deferred"},
                [],
                {"igraph_deferred": ConfiguredDisposition("deferred", "example", "Later.")},
                set(),
            )
        with self.assertRaisesRegex(ValueError, "references missing Go API MissingAPI"):
            validate_inventory(
                declarations,
                set(),
                [],
                {
                    "igraph_deferred": ConfiguredDisposition(
                        "composed", "example", "Composed by another API.", "MissingAPI"
                    )
                },
                set(),
            )

    def test_renders_all_inventory_classifications_deterministically(self):
        declarations = {
            "igraph_bound": "b.h",
            "igraph_composed": "a.h",
            "igraph_deferred": "a.h",
            "igraph_internal": "a.h",
            "igraph_missing": "a.h",
            "igraph_unsupported": "b.h",
        }
        annotations = [
            Annotation("bind", "igraph_bound", "Bound", "graph.go", 1),
            Annotation("internal", "igraph_internal", "helper", "graph.go", 2),
        ]
        config = {
            "upstream": "igraph/igraph",
            "version": "1",
            "release_url": "https://example.test",
            "dispositions": {
                "composed": {
                    "igraph_composed": {
                        "go_api": "Composed",
                        "domain": "example",
                        "rationale": "Composed by a bounded API.",
                    }
                },
                "deferred": {
                    "igraph_deferred": {
                        "domain": "later",
                        "rationale": "Planned for a later milestone.",
                    }
                },
                "intentionally_unsupported": {
                    "igraph_unsupported": {
                        "domain": "low-level",
                        "rationale": "C handles are not public.",
                    }
                },
            },
        }
        report = render(config, declarations, annotations)
        reordered_config = dict(config)
        reordered_config["dispositions"] = dict(reversed(list(config["dispositions"].items())))
        reordered_declarations = dict(reversed(list(declarations.items())))
        self.assertEqual(report, render(reordered_config, reordered_declarations, annotations))
        self.assertIn(
            "Headers marked `(generated)` are declaration-discovery locations.",
            report,
        )
        self.assertIn("| `igraph_bound` | `b.h` | User-facing | `Bound` |", report)
        self.assertIn("- Composed APIs: **1**", report)
        self.assertIn("- User-facing bindings: **1 / 6 (16.67%)**", report)
        self.assertIn("- Internal dependencies: **1**", report)
        self.assertIn("- Intentionally unsupported: **1**", report)
        self.assertIn("- Deferred declarations: **1**", report)
        self.assertIn("| `igraph_composed` | `a.h` | Composed | `Composed` |", report)
        self.assertIn("| `igraph_deferred` | `a.h` | Deferred | — |", report)
        self.assertIn("| `igraph_internal` | `a.h` | Internal | `helper` |", report)
        self.assertIn("| `igraph_unsupported` | `b.h` | Intentionally unsupported | — |", report)
        self.assertIn("| `igraph_missing` | `a.h` | Missing | — |", report)


if __name__ == "__main__":
    unittest.main()
